<?php
declare(strict_types=1);
require __DIR__.'/bootstrap.php';
$u=requireUser();requireAdmin($u);if((int)$u['must_change'])fail('初回パスワードを変更してください。',403);
if(($_SERVER['REQUEST_METHOD']??'GET')!=='GET')fail('この画面は検索・閲覧専用です。',405);
function asTable(string $name):bool{return (bool)query("SELECT 1 FROM sqlite_master WHERE type='table' AND name=?",[$name])->fetchColumn();}
function asParam(string $key,int $max=80):string{return value($_GET,$key,$max);}
function asEnum(string $key,array $values):string{$v=asParam($key);if(!in_array($v,$values,true))fail('検索条件をご確認ください。');return $v;}
$tabs=['members'=>'会員を探す','events'=>'Zoom・お知らせ','minutes'=>'議事録','redo'=>'REDO MAIL','prayer'=>'祈りの提出状況','mail'=>'メール配信'];
$tab=asParam('tab')?:'members';if(!isset($tabs[$tab]))fail('ページが見つかりません。',404);
$q=asParam('q');$area=asParam('area',60);$role=asEnum('role',['','member','candidate','director','admin']);$membership=asEnum('membership',['','free','regular']);$active=asEnum('active',['','0','1']);$submitted=asEnum('submitted',['','yes','no']);$state=asEnum('state',['','draft','published']);
$month=asParam('month',7)?:date('Y-m',strtotime('first day of last month'));$dt=DateTimeImmutable::createFromFormat('!Y-m',$month);if(!$dt||$dt->format('Y-m')!==$month)fail('対象月を確認してください。');
$from=asParam('from',10);$to=asParam('to',10);foreach([$from,$to] as $day){if($day!==''){$d=DateTimeImmutable::createFromFormat('!Y-m-d',$day);if(!$d||$d->format('Y-m-d')!==$day)fail('日付を確認してください。');}}if($from!==''&&$to!==''&&$from>$to)fail('開始日は終了日以前にしてください。');
$page=filter_var($_GET['page']??1,FILTER_VALIDATE_INT,['options'=>['min_range'=>1,'max_range'=>100000]]);if($page===false)fail('ページ番号を確認してください。');$offset=($page-1)*30;
$id=filter_var($_GET['member']??0,FILTER_VALIDATE_INT,['options'=>['min_range'=>0]]);if($id===false)fail('会員番号を確認してください。');
$roles=['member'=>'一般会員','candidate'=>'理事候補','director'=>'理事','admin'=>'管理者'];$tiers=['free'=>'無料会員','regular'=>'通常会員'];
$e=fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');
function asLink(array $replace=[]):string{return '?'.http_build_query(array_merge($_GET,$replace));}
$rows=[];$total=0;$unavailable=false;$member=null;$learning=[];$terms=[];$reports=[];$regions=[];
if($id){
 $member=query('SELECT id,name,login,role,membership,active,created_at,chat_access FROM users WHERE id=? AND deleted_at=0',[$id])->fetch();if(!$member)fail('会員が見つかりません。',404);
 if(asTable('learning_notes'))$learning=query('SELECT lesson_id,watched,updated_at FROM learning_notes WHERE user_id=? ORDER BY lesson_id',[$id])->fetchAll();
 if(asTable('redo_terms'))$terms=query('SELECT year,joined_on,paid_on,amount,enabled FROM redo_terms WHERE user_id=? ORDER BY year DESC LIMIT 10',[$id])->fetchAll();
 if(asTable('prayer_reports'))$reports=query('SELECT month,updated_at FROM prayer_reports WHERE user_id=? ORDER BY month DESC LIMIT 12',[$id])->fetchAll();
 if(asTable('mail_regions'))$regions=query('SELECT area FROM mail_regions WHERE user_id=? ORDER BY area',[$id])->fetchAll(PDO::FETCH_COLUMN);
}else{
 $params=[];$where=[];$source='';$select='';$order='';
 if($tab==='members'){
  $source='users u';$select='u.id,u.name,u.login,u.role,u.membership,u.active';$where[]='u.deleted_at=0';$order='u.id DESC';
  if($q!==''){$where[]='(instr(u.name,?)>0 OR instr(lower(u.login),lower(?))>0)';array_push($params,$q,$q);}
  foreach(['role'=>$role,'membership'=>$membership,'active'=>$active] as $k=>$v)if($v!==''){$where[]='u.'.$k.'=?';$params[]=$v;}
  if($area!==''){if(asTable('mail_regions')){$where[]='EXISTS(SELECT 1 FROM mail_regions r WHERE r.user_id=u.id AND r.area=?)';$params[]=$area;}else{$where[]='0=1';}}
 }elseif($tab==='prayer'){
  if(!asTable('prayer_members')||!asTable('prayer_reports'))$unavailable=true;
  else{$source='users u JOIN prayer_members pm ON pm.user_id=u.id LEFT JOIN prayer_reports pr ON pr.user_id=u.id AND pr.month=?';$params[]=$month;$select='u.id,u.name,pm.number,pr.id report_id,pr.updated_at';$order='pm.number';$where=['u.deleted_at=0','u.active=1','pm.enabled=1','pm.start_month<=?',"(pm.end_month='' OR pm.end_month>=?)"];array_push($params,$month,$month);if($q!==''){$where[]='instr(u.name,?)>0';$params[]=$q;}if($submitted!=='')$where[]=$submitted==='yes'?'pr.id IS NOT NULL':'pr.id IS NULL';if($area!==''){if(asTable('mail_regions')){$where[]='EXISTS(SELECT 1 FROM mail_regions r WHERE r.user_id=u.id AND r.area=?)';$params[]=$area;}else $where[]='0=1';}}
 }else{
  $defs=[
   'events'=>['messages','id,title,body,event_at,area,room,created_at','COALESCE(NULLIF(event_at,\'\'),datetime(created_at,\'unixepoch\',\'+9 hours\'))','created_at DESC',"kind='notice' AND hidden=0"],
   'minutes'=>['meeting_minutes','id,title,meeting_on,published','meeting_on','meeting_on DESC,id DESC','1=1'],
   'redo'=>['redo_issues','id,title,number,issued_on,published','issued_on','issued_on DESC,id DESC','1=1'],
   'mail'=>['mail_bulletins','id,title,kind,audience,state,created_at','date(created_at,\'unixepoch\',\'+9 hours\')','id DESC','1=1']
  ];[$source,$select,$datefield,$order,$initial]=$defs[$tab];if(!asTable($source))$unavailable=true;$where[]=$initial;
  if($q!==''){$where[]=$tab==='redo'?'(instr(title,?)>0 OR instr(number,?)>0 OR instr(body,?)>0)':'(instr(title,?)>0 OR instr(body,?)>0)';array_push($params,$q,$q);if($tab==='redo')$params[]=$q;}
  if($from!==''){$where[]='substr('.$datefield.',1,10)>=?';$params[]=$from;}if($to!==''){$where[]='substr('.$datefield.',1,10)<=?';$params[]=$to;}
  if($tab==='events'&&$area!==''){$where[]='area=?';$params[]=$area;}
  if($state!==''&&in_array($tab,['minutes','redo','mail'],true)){$where[]=$tab==='mail'?'state=?':'published=?';$params[]=$tab==='mail'?$state:($state==='published'?1:0);}
 }
 if(!$unavailable){$sql=' FROM '.$source.' WHERE '.implode(' AND ',$where);$total=(int)query('SELECT COUNT(*)'.$sql,$params)->fetchColumn();$rows=query('SELECT '.$select.$sql.' ORDER BY '.$order.' LIMIT 30 OFFSET '.$offset,$params)->fetchAll();}
}
header('Content-Type: text/html; charset=utf-8');header('Cache-Control: no-store');header("Content-Security-Policy: default-src 'self'; script-src 'none'; style-src 'self'; object-src 'none'; base-uri 'none'; form-action 'self'; frame-ancestors 'none'");
?>
<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>管理者の検索ページ｜じねんネットワーク</title><link rel="stylesheet" href="admin-search.css"></head><body><aside><div class="brand">じねん<br>ネットワーク</div><p>管理者の検索ページ</p><nav aria-label="管理メニュー"><?php foreach($tabs as $k=>$v):?><a href="?tab=<?= $k ?>" <?= $tab===$k?'aria-current="page"':'' ?>><?= $v ?></a><?php endforeach;?><a href="./?account=1">従来の管理画面へ ↗</a><a href="../ku-fudo-demo/">会員サイトへ ↗</a></nav></aside><div class="workspace"><header><strong>じねんネットワーク ／ 管理者用</strong><span>検索・閲覧</span></header><main>
<?php if($member):?><a href="<?= $e(asLink(['member'=>null])) ?>">← 検索結果へ戻る</a><h1><?= $e($member['name']) ?>さん</h1><section class="panel"><h2>登録情報</h2><dl><?php foreach(['メールアドレス'=>$member['login'],'役職'=>$roles[$member['role']],'会員区分'=>$tiers[$member['membership']]??$member['membership'],'利用状態'=>(int)$member['active']?'利用中':'停止中','所属地区'=>$regions?implode('、',$regions):'未設定','登録日'=>date('Y/m/d',(int)$member['created_at'])] as $k=>$v):?><dt><?= $e($k) ?></dt><dd><?= $e($v) ?></dd><?php endforeach;?></dl></section><div class="cards"><section class="panel"><h2>視聴状況</h2><p>本人がチェックして保存した記録です。</p><?php $titles=['yUsA5PHWJeg'=>'自明行とは何か（前半）','ZQJCpaHgnEc'=>'自明行とは何か（後半）','k3bWGxIxn4g'=>'自明行の導入','uk5PHAL4w0U'=>'正しい喜びの自覚','6EJ4ZIFUxPk'=>'自明行の準備','lNlSeXO-YSA'=>'自明行の落とし穴'];$records=array_column($learning,null,'lesson_id');foreach($titles as $lid=>$title):?><p><span class="badge"><?= (int)($records[$lid]['watched']??0)?'視聴済み':'未チェック' ?></span> <?= $e($title) ?></p><?php endforeach;?><small>本人のメモは取得・表示しません。</small></section><section class="panel"><h2>祈りの提出履歴</h2><p>直近12件の提出月です。</p><?php if(!$reports):?><p>提出記録はありません。</p><?php endif;?><?php foreach($reports as $r):?><p><?= $e($r['month']) ?> ／ 提出済み</p><?php endforeach;?></section></div><section class="panel"><h2>やりなおし会員・会費記録</h2><?php if(!$terms):?><p>登録記録はありません。</p><?php endif;?><?php foreach($terms as $t):?><p><?= (int)$t['year'] ?>年度 ／ <?= (int)$t['enabled']?'有効設定':'停止設定' ?> ／ 入金日 <?= $e($t['paid_on']) ?> ／ <?= number_format((int)$t['amount']) ?>円</p><?php endforeach;?><small>年度は2月から翌年1月。過去年度の有効設定は、現在の会員資格を意味しません。</small></section>
<?php else:?><div class="heading"><div><p class="eyebrow">MANAGEMENT</p><h1><?= $tabs[$tab] ?></h1></div><p>条件を選んで、必要な情報を探せます。</p></div><form class="panel search" method="get"><input type="hidden" name="tab" value="<?= $tab ?>"><div class="fields"><label><?= $tab==='members'?'名前・メールアドレス':($tab==='prayer'?'会員名':'キーワード') ?><input name="q" maxlength="80" value="<?= $e($q) ?>" placeholder="一部の文字でも検索できます"></label><?php if(in_array($tab,['members','prayer','events'],true)):?><label>地区名<input name="area" value="<?= $e($area) ?>" maxlength="60" placeholder="例：福岡（登録名と一致）"></label><?php endif;?><?php if($tab==='prayer'):?><label>対象月<input name="month" type="month" value="<?= $e($month) ?>"></label><label>提出状況<select name="submitted"><?php foreach([''=>'すべて','yes'=>'提出済み','no'=>'未提出'] as $k=>$v):?><option value="<?= $k ?>" <?= $submitted===$k?'selected':'' ?>><?= $v ?></option><?php endforeach;?></select></label><?php elseif($tab!=='members'):?><label>開始日<input name="from" type="date" value="<?= $e($from) ?>"></label><label>終了日<input name="to" type="date" value="<?= $e($to) ?>"></label><?php endif;?></div>
<?php if($tab==='members'):?><details <?= $role!==''||$membership!==''||$active!==''?'open':'' ?>><summary>詳しく絞り込む</summary><div class="fields"><?php foreach(['role'=>['役職',[''=>'すべて']+$roles,$role],'membership'=>['会員区分',[''=>'すべて']+$tiers,$membership],'active'=>['利用状態',[''=>'すべて','1'=>'利用中','0'=>'停止中'],$active]] as $key=>[$label,$options,$selected]):?><label><?= $label ?><select name="<?= $key ?>"><?php foreach($options as $k=>$v):?><option value="<?= $e($k) ?>" <?= (string)$selected===(string)$k?'selected':'' ?>><?= $v ?></option><?php endforeach;?></select></label><?php endforeach;?></div></details><?php elseif(in_array($tab,['minutes','redo','mail'],true)):?><label>公開状態<select name="state"><?php foreach([''=>'すべて','draft'=>'下書き','published'=>'公開済み'] as $k=>$v):?><option value="<?= $k ?>" <?= $state===$k?'selected':'' ?>><?= $v ?></option><?php endforeach;?></select></label><?php endif;?><div class="actions"><button>この条件で検索</button><a href="?tab=<?= $tab ?>">条件をクリア</a></div></form>
<?php if($unavailable):?><section class="panel"><h2>この機能のデータはまだありません</h2><p>対応する機能の設置・初期設定後に検索できます。既存データの変更は行いません。</p></section><?php else:?><p class="count"><?= number_format($total) ?>件 ／ <?= number_format($page) ?>ページ目</p><div class="panel table-wrap"><table><thead><tr><?php foreach($tab==='members'?['会員名','メール','区分・役職','状態']:($tab==='prayer'?['番号','会員名','対象月','提出状況']:['タイトル','日付・番号','対象・状態','詳細']) as $h):?><th><?= $h ?></th><?php endforeach;?></tr></thead><tbody>
<?php foreach($rows as $r):?><tr><?php if($tab==='members'):?><td><a href="<?= $e(asLink(['member'=>$r['id']])) ?>"><?= $e($r['name']) ?></a></td><td><?= $e($r['login']) ?></td><td><?= $e(($tiers[$r['membership']]??$r['membership']).' ／ '.$roles[$r['role']]) ?></td><td><span class="badge"><?= (int)$r['active']?'利用中':'停止中' ?></span></td><?php elseif($tab==='prayer'):?><td><?= (int)$r['number'] ?></td><td><a href="<?= $e(asLink(['member'=>$r['id']])) ?>"><?= $e($r['name']) ?></a></td><td><?= $e($month) ?></td><td><span class="badge"><?= $r['report_id']?'提出済み':'未提出' ?></span></td><?php else:
 $link=match($tab){'events'=>'./?room='.$r['room'],'minutes'=>'operations.php?id='.$r['id'],'redo'=>'redo.php?id='.$r['id'],'mail'=>'mail-center.php?id='.$r['id']};
 $date=match($tab){'events'=>$r['event_at']?:date('Y/m/d',(int)$r['created_at']),'minutes'=>$r['meeting_on'],'redo'=>$r['issued_on'].' ／ No.'.$r['number'],'mail'=>date('Y/m/d H:i',(int)$r['created_at'])};
 $status=match($tab){'events'=>($r['room']==='board'?'理事・理事候補':'全体').' ／ '.$r['area'],'minutes','redo'=>(int)$r['published']?'公開済み':'下書き','mail'=>$r['state']==='draft'?'下書き':'公開済み'};
 ?><td><?= $e($r['title']) ?><?php if($tab==='events'):?><p class="excerpt"><?= $e(mb_substr($r['body'],0,160)) ?></p><?php endif;?></td><td><?= $e($date) ?></td><td><?= $e($status) ?></td><td><a href="<?= $e($link) ?>">開く →</a></td><?php endif;?></tr><?php endforeach;?>
<?php if(!$rows):?><tr><td colspan="4">該当するデータはありません。条件を減らしてお試しください。</td></tr><?php endif;?></tbody></table></div><div class="pager"><?php if($page>1):?><a href="<?= $e(asLink(['page'=>$page-1])) ?>">← 前の30件</a><?php endif;?><?php if($page*30<$total):?><a href="<?= $e(asLink(['page'=>$page+1])) ?>">次の30件 →</a><?php endif;?></div><?php endif;?><?php endif;?>
</main><footer>検索専用の別ページです。登録・編集・配信は従来の各管理画面で行います。</footer></div></body></html>
