<?php
header('Cache-Control: no-store, private');
header('X-Robots-Tag: noindex, nofollow');
header('X-Content-Type-Options: nosniff');
header('Referrer-Policy: no-referrer');
header("Content-Security-Policy: default-src 'self'; script-src 'self'; style-src 'self'; connect-src 'self'; img-src 'self'; object-src 'none'; base-uri 'none'; form-action 'self'; frame-ancestors 'none'");
?>
<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>献文舎｜会員チャット</title><link rel="stylesheet" href="chat.css?v=20260909-clear"></head>
<body><header class="masthead"><a href="./" class="brand">献文舎 <span>会員チャット</span></a><span class="private-tag">会員限定</span></header>
<nav id="navigation" class="navigation" aria-label="チャットメニュー" hidden><button data-room="all" aria-pressed="true">全体</button><button data-room="board" aria-pressed="false" id="board-button" hidden>理事＆理事候補</button><a href="#zoom-schedule">Zoom予定</a><a href="#account">アカウント</a></nav>
<main><div id="status" role="status" aria-live="polite">接続を確認しています…</div><noscript>チャットの利用にはJavaScriptを有効にしてください。</noscript>
<section id="invite-panel" class="card narrow" hidden><p class="eyebrow">WELCOME</p><h1>会員チャットへようこそ</h1><p>お名前やパスワードの入力は不要です。</p><form id="invite-form"><button class="primary enter-chat">チャットに入る →</button><label class="remember-option"><input type="checkbox" name="remember" checked>この端末で30日間ログインを保つ</label><small>ご自身のスマホ・パソコンでご利用ください。共有の端末ではチェックを外してください。</small></form><div id="invite-existing" hidden><p id="invite-identity"></p><button type="button" class="primary" id="invite-current">このアカウントでチャットを開く</button><button type="button" class="secondary" id="invite-switch">ログアウトして専用リンクを使う</button></div><p><small>このリンクを個別に受け取ったご本人だけがご利用ください。リンクは発行から3日間・1回限り有効です。</small></p><button type="button" class="secondary" id="invite-cancel">通常のログイン画面に戻る</button></section>
<section id="login-panel" class="card narrow" hidden><p class="eyebrow">MEMBERS</p><h1>会員チャットにログイン</h1><p>専用リンクを受け取った方は、そのリンクを開くと入力なしで入れます。メールアドレスでログインする方は、以下をご利用ください。</p><form id="login-form"><label>メールアドレス<input name="login" type="text" inputmode="email" autocomplete="username" autocapitalize="none" spellcheck="false" required maxlength="254" placeholder="例：name@example.com"></label><label>パスワード<input name="password" type="password" autocomplete="current-password" required maxlength="72"></label><button class="primary">ログイン</button></form><small>以前のIDで登録済みの方は、そのIDでもログインできます。</small><small>登録・パスワード再発行は献文舎の管理者へご連絡ください。</small></section>
<section id="setup-panel" class="card narrow" hidden><p class="eyebrow">INITIAL SETUP</p><h1>管理者の初期設定</h1><p>設置担当者が一度だけ行う設定です。</p><form id="setup-form"><label>初期設定キー<input name="setup_key" type="password" required minlength="32" autocomplete="off"></label><label>管理者の表示名<input name="name" required maxlength="60"></label><label>管理者のメールアドレス<input name="login" type="email" required maxlength="254" autocomplete="username" autocapitalize="none" spellcheck="false" placeholder="例：name@example.com"></label><label>パスワード（8文字以上）<input name="password" type="password" required minlength="8" maxlength="72" autocomplete="new-password"></label><button class="primary">管理者を作成</button></form><small>設定後は非公開config.phpのsetup_keyを空に戻してください。</small></section>
<section id="chat-panel" hidden><div class="room-heading"><div><h1 id="room-title">全体チャット</h1><p id="room-description" hidden>全会員へのお知らせと交流の場です。</p></div><button id="refresh" class="secondary">更新する</button></div>
<a id="next-zoom" class="next-zoom" href="#zoom-schedule" hidden><span class="next-zoom-label">次のZoom</span><strong id="next-zoom-date"></strong><span id="next-zoom-title"></span><span aria-hidden="true">予定を見る ↓</span></a>
<div class="chat-layout"><section class="conversation" aria-label="投稿一覧"><small class="message-order">新しい投稿が上に表示されます</small><div id="messages"></div><button class="secondary older" id="older" hidden>以前の投稿を読む</button>
</section>
<section class="events card" id="zoom-schedule" tabindex="-1"><div class="section-heading"><h2>これからのZoom</h2><span>日本時間</span></div><div id="events"></div></section>
<section class="card composer" id="composer"><h2>メッセージを投稿</h2><form id="post-form"><div class="reply-to" id="reply-to" hidden><span id="reply-label"></span><button type="button" id="cancel-reply">返信を解除</button></div><input type="hidden" name="parent_id" value="0"><label id="kind-label" hidden>投稿の種類<select name="kind"><option value="chat">通常のメッセージ</option><option value="notice">献文舎からのお知らせ</option></select></label><fieldset id="notice-fields" hidden><legend>お知らせの詳細</legend><label>会議名・お知らせのタイトル<input name="title" maxlength="120" placeholder="例：福岡地区 学びの交流会"></label><div class="fields"><label>対象地区<input name="area" maxlength="60" placeholder="例：全地区・福岡"></label><label>開催日時（日本時間）<input name="event_at" type="datetime-local"></label></div><label>Zoom参加リンク<input name="zoom_url" type="url" maxlength="1500" placeholder="https://…"></label><small>日時・地区・リンクは任意です。会議予定以外のお知らせも投稿できます。</small></fieldset><label><span id="body-label">メッセージ</span><textarea name="body" rows="4" maxlength="3000" required placeholder="お知らせ、質問、気づきなどをお書きください。"></textarea></label><div class="post-bottom"><small id="post-room">送信先：全体チャット</small><button class="primary">投稿する</button></div></form></section>
</div>
</section>
<section id="account" class="card" hidden><div class="section-heading"><h2>アカウント</h2><button class="secondary" id="logout">ログアウト</button></div><p id="identity"></p><p id="link-account-note" hidden>専用リンクでログインしています。このページをブックマークして、次回も同じブラウザで開いてください。ログインできなくなった場合は、管理者に新しい専用リンクをご依頼ください。メールアドレス・パスワードの設定変更も管理者へご連絡ください。</p><p id="password-required" hidden>仮パスワードでログインしています。チャットの利用前に、ご自身のパスワードに変更してください。</p><details id="password-details"><summary>パスワードを変更する</summary><form id="password-form"><label>現在のパスワード<input name="old_password" type="password" autocomplete="current-password" required maxlength="72"></label><label>新しいパスワード（8文字以上）<input name="password" type="password" autocomplete="new-password" minlength="8" maxlength="72" required></label><button class="primary">パスワードを変更</button></form></details>
<details id="email-details"><summary>ログイン用メールアドレスを設定・変更する</summary><p>従来のIDで登録した方も、ここでメールアドレスへ切り替えられます。変更後は以前のID・メールアドレスではログインできません。</p><form id="email-form"><label>新しいメールアドレス<input name="login" type="email" required maxlength="254" autocomplete="email" autocapitalize="none" spellcheck="false"></label><label>現在のパスワード<input name="password" type="password" required maxlength="72" autocomplete="current-password"></label><button class="primary">メールアドレスを保存</button></form><small>確認メールは送信されません。入力内容をよく確認してください。</small></details>
<section id="admin-panel" hidden><hr><h2>会員管理</h2><p>登録した方だけがログインできます。会員は最大500件まで一覧表示します。</p><details><summary>会員を追加する</summary><form id="user-form"><div class="fields"><label>表示名<input name="name" required maxlength="60"></label><label>メールアドレス<input name="login" type="email" required maxlength="254" autocomplete="off" autocapitalize="none" spellcheck="false" placeholder="例：name@example.com"></label></div><label>権限<select name="role"><option value="member">一般会員</option><option value="candidate">理事候補</option><option value="director">理事</option><option value="admin">管理者（会員管理・お知らせ投稿可）</option></select></label><label>ログインの案内方法<select name="access_method"><option value="link">専用リンク（入力不要・おすすめ）</option><option value="password">メールアドレスと仮パスワード</option></select></label><small>管理者の追加は、メールアドレスと仮パスワード方式になります。</small><button class="primary">会員を追加して案内を作る</button></form></details><div id="users"></div></section></section>
<footer>献文舎 会員チャット <span>投稿や参加リンクを会員以外へ共有しないでください。</span></footer></main>
<button class="back-top" id="top" aria-label="ページの先頭へ戻る" hidden>↑</button><dialog id="credential-dialog" aria-labelledby="credential-heading"><h2 id="credential-heading">仮パスワードを発行しました</h2><p id="credential-description">この画面を閉じると再表示できません。本人に個別に伝えてください。</p><p id="credential-user"></p><output id="credential"></output><p id="credential-note">初回ログイン時に変更が必要です。</p><button type="button" class="primary" id="credential-copy">案内文をコピー</button><button type="button" class="secondary" id="credential-close">閉じる</button></dialog><script src="chat.js?v=20260909-clear"></script></body></html>
