<?php
header('Cache-Control: no-store, private');
header('X-Robots-Tag: noindex, nofollow');
header('X-Content-Type-Options: nosniff');
header('Referrer-Policy: no-referrer');
header("Content-Security-Policy: default-src 'self'; script-src 'self'; style-src 'self'; connect-src 'self'; img-src 'self'; object-src 'none'; base-uri 'none'; form-action 'self'; frame-ancestors 'none'");
?>
<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>じねんネットワーク｜会員サイト</title><link rel="stylesheet" href="chat.css?v=20260911-prayer"></head>
<body><header class="masthead"><a href="./" class="brand">じねんネットワーク <span>会員サイト</span></a><span class="private-tag">会員限定</span></header>
<nav id="navigation" class="navigation" aria-label="チャットメニュー" hidden><a href="?room=all" data-room="all" aria-current="page">チャット</a><a href="?room=board" data-room="board" id="board-button" hidden>理事＆理事候補</a><a id="zoom-nav" href="?room=all#zoom-schedule">Zoom予定</a><a id="materials-nav" href="../ku-fudo-demo/">カリキュラム</a><a href="redo.php">REDO MAIL</a><a href="prayer.php">祈りの蓄積</a><a href="#account">アカウント</a></nav>
<main><div id="status" role="status" aria-live="polite">接続を確認しています…</div><noscript>チャットの利用にはJavaScriptを有効にしてください。</noscript>
<section id="invite-panel" class="card narrow" hidden><p class="eyebrow">WELCOME</p><h1>会員チャットへようこそ</h1><p>お名前やパスワードの入力は不要です。</p><form id="invite-form"><button class="primary enter-chat">チャットに入る →</button><label class="remember-option"><input type="checkbox" name="remember" checked>この端末で30日間ログインを保つ</label><small>ご自身のスマホ・パソコンでご利用ください。共有の端末ではチェックを外してください。</small></form><div id="invite-existing" hidden><p id="invite-identity"></p><button type="button" class="primary" id="invite-current">このアカウントでチャットを開く</button><button type="button" class="secondary" id="invite-switch">ログアウトして専用リンクを使う</button></div><p><small>このリンクを個別に受け取ったご本人だけがご利用ください。リンクは発行から3日間・1回限り有効です。</small></p><button type="button" class="secondary" id="invite-cancel">通常のログイン画面に戻る</button></section>
<section id="login-panel" class="card narrow" hidden><p class="eyebrow">MEMBERS</p><h1>会員サイトにログイン</h1><p><a class="signup-link" href="?register=1">初めての方はこちら → 会員登録</a></p><form id="login-form"><label>メールアドレス<input name="login" type="text" inputmode="email" autocomplete="username" autocapitalize="none" spellcheck="false" required maxlength="254" placeholder="例：name@example.com"></label><label>パスワード<input name="password" type="password" autocomplete="current-password" required maxlength="72"></label><label class="remember-option"><input type="checkbox" name="remember" checked>この端末でログインを保つ（30日間）</label><small>共有の端末ではチェックを外してください。</small><button class="primary">ログイン</button></form><small>以前のIDで登録済みの方は、そのIDでもログインできます。</small><small>パスワードを忘れた方は管理者へご連絡ください。</small></section>
<section id="register-panel" class="card narrow" hidden><h1>会員登録</h1><p>無料会員も全体チャットに参加できます。管理者の承認後にご利用いただけます。</p><form id="register-form"><label>お名前<input name="name" required maxlength="60" autocomplete="name" placeholder="例：山田 花子"></label><label>メールアドレス<input name="login" type="email" required maxlength="254" autocomplete="email" autocapitalize="none" spellcheck="false" placeholder="例：name@example.com"></label><label>パスワード（8文字以上）<input id="register-password" name="password" type="password" required minlength="8" maxlength="72" autocomplete="new-password"></label><label class="remember-option"><input id="show-register-password" type="checkbox">パスワードを表示する</label><p>コースのご案内のため、管理者が視聴状況を確認します。自分のメモは管理画面には表示されません。</p><button class="primary">登録を申し込む</button></form><div id="register-success" role="status" hidden><h2>申し込みを受け付けました</h2><p>管理者からの連絡をお待ちください。承認後は、入力したメールアドレスとパスワードでログインできます。</p><p>登録済みの方は、そのままログインしてください。</p></div><p><a href="./">← ログイン画面へ</a></p></section>
<section id="setup-panel" class="card narrow" hidden><p class="eyebrow">INITIAL SETUP</p><h1>管理者の初期設定</h1><p>設置担当者が一度だけ行う設定です。</p><form id="setup-form"><label>初期設定キー<input name="setup_key" type="password" required minlength="32" autocomplete="off"></label><label>管理者の表示名<input name="name" required maxlength="60"></label><label>管理者のメールアドレス<input name="login" type="email" required maxlength="254" autocomplete="username" autocapitalize="none" spellcheck="false" placeholder="例：name@example.com"></label><label>パスワード（8文字以上）<input name="password" type="password" required minlength="8" maxlength="72" autocomplete="new-password"></label><button class="primary">管理者を作成</button></form><small>設定後は非公開config.phpのsetup_keyを空に戻してください。</small></section>
<section id="chat-panel" hidden><div class="room-heading"><div><h1 id="room-title">全体チャット</h1><p id="room-description" hidden>全会員へのお知らせと交流の場です。</p></div><button id="refresh" class="secondary">更新する</button></div>
<div class="learning-shortcut"><a class="primary" href="../ku-fudo-demo/">カリキュラムを見る →</a><p>上のメニューの「カリキュラム」からも開けます。</p></div>
<a id="next-zoom" class="next-zoom" href="#zoom-schedule" hidden><span class="next-zoom-label">次のZoom</span><strong id="next-zoom-date"></strong><span id="next-zoom-title"></span><span aria-hidden="true">予定を見る ↓</span></a>
<div class="chat-layout"><section class="conversation" aria-label="投稿一覧"><small class="message-order">新しい投稿が上に表示されます</small><div id="messages"></div><button class="secondary older" id="older" hidden>以前の投稿を読む</button>
</section>
<section class="events card" id="zoom-schedule" tabindex="-1"><div class="section-heading"><h2>これからのZoom</h2><span>日本時間</span></div><div id="events"></div></section>
<section class="card composer" id="composer"><h2>メッセージを投稿</h2><p id="moderation-note" hidden>無料会員の投稿・返信は、管理者の承認後に表示されます。</p><div id="own-submissions"></div><form id="post-form"><div class="reply-to" id="reply-to" hidden><span id="reply-label"></span><button type="button" id="cancel-reply">返信を解除</button></div><input type="hidden" name="parent_id" value="0"><label id="kind-label" hidden>投稿の種類<select name="kind"><option value="chat">通常のメッセージ</option><option value="notice">じねんネットワークからのお知らせ</option></select></label><fieldset id="notice-fields" hidden><legend>お知らせの詳細</legend><label>会議名・お知らせのタイトル<input name="title" maxlength="120" placeholder="例：福岡地区 学びの交流会"></label><div class="fields"><label>対象地区<input name="area" maxlength="60" placeholder="例：全地区・福岡"></label><label>開催日時（日本時間）<input name="event_at" type="datetime-local"></label></div><label>Zoom参加リンク<input name="zoom_url" type="url" maxlength="1500" placeholder="https://…"></label><small>日時・地区・リンクは任意です。会議予定以外のお知らせも投稿できます。</small></fieldset><label><span id="body-label">メッセージ</span><textarea name="body" rows="4" maxlength="3000" required placeholder="お知らせ、質問、気づきなどをお書きください。"></textarea></label><div class="post-bottom"><small id="post-room">送信先：全体チャット</small><button class="primary">投稿する</button></div></form></section>
</div>
</section>
<section id="materials-panel" hidden><div class="section-heading"><h1>会員教材</h1><a class="secondary" href="?room=all">チャットへ</a></div><p id="materials-membership"></p><div id="materials-list"></div><article id="material-detail" class="card" hidden><a href="?view=materials">← 教材一覧に戻る</a><h2 id="material-title"></h2><p id="material-body" class="message-body"></p><a id="material-resource" class="primary" hidden>動画・教材を開く →</a><div id="material-admin-actions" hidden><button type="button" id="material-edit" class="secondary">この教材を編集</button><button type="button" id="material-delete" class="secondary danger">教材を削除</button></div></article><section id="material-editor-section" class="card" hidden><details id="material-editor"><summary>教材を追加・編集する</summary><form id="material-form"><input name="id" type="hidden" value="0"><label>教材名<input name="title" required maxlength="120"></label><label>教材の本文・学ぶこと<textarea name="body" required maxlength="6000" rows="6"></textarea></label><label>動画・教材のリンク<input name="resource_url" type="url" maxlength="1500" placeholder="https://…"></label><small>動画など外部リンク先の公開範囲は、配信元でも設定してください。</small><label>閲覧できる会員<select name="audience"><option value="free">無料会員を含む全会員</option><option value="regular">通常会員のみ</option></select></label><label>公開状態<select name="published"><option value="0">下書き</option><option value="1">公開する</option></select></label><label>表示順（小さい数字から）<input name="sort_order" type="number" min="0" max="9999" value="0" required></label><button class="primary">教材を保存</button><button type="button" id="material-new" class="secondary">新しい教材を入力</button></form></details></section></section>
<section id="account" class="card" hidden><div class="section-heading"><h2>アカウント</h2><button class="secondary" id="logout">ログアウト</button></div><p id="identity"></p><p><a href="redo.php">REDO MAILへ戻る →</a> ／ <a href="prayer.php">祈りの蓄積へ戻る →</a></p><p id="link-account-note" hidden>専用リンクでログインしています。このページをブックマークして、次回も同じブラウザで開いてください。ログインできなくなった場合は、管理者に新しい専用リンクをご依頼ください。メールアドレス・パスワードの設定変更も管理者へご連絡ください。</p><p id="password-required" hidden>仮パスワードでログインしています。チャットの利用前に、ご自身のパスワードに変更してください。</p><details id="password-details"><summary>パスワードを変更する</summary><form id="password-form"><label>現在のパスワード<input name="old_password" type="password" autocomplete="current-password" required maxlength="72"></label><label>新しいパスワード（8文字以上）<input name="password" type="password" autocomplete="new-password" minlength="8" maxlength="72" required></label><button class="primary">パスワードを変更</button></form></details>
<details id="email-details"><summary>ログイン用メールアドレスを設定・変更する</summary><p>従来のIDで登録した方も、ここでメールアドレスへ切り替えられます。変更後は以前のID・メールアドレスではログインできません。</p><form id="email-form"><label>新しいメールアドレス<input name="login" type="email" required maxlength="254" autocomplete="email" autocapitalize="none" spellcheck="false"></label><label>現在のパスワード<input name="password" type="password" required maxlength="72" autocomplete="current-password"></label><button class="primary">メールアドレスを保存</button></form><small>確認メールは送信されません。入力内容をよく確認してください。</small></details>
<section id="admin-panel" hidden><hr><p><a class="secondary" href="learning-admin.php">会員の視聴状況を確認する →</a></p><h2>投稿の承認</h2><button type="button" id="submissions-refresh" class="secondary">承認待ちを確認</button><div id="submissions"></div><h2>会員管理</h2><p><a class="secondary" href="prayer.php?manage=1">祈りの蓄積・参加者の管理 →</a></p><p><a class="secondary" href="redo.php">やりなおし会員・REDO MAILの管理 →</a></p><section aria-labelledby="applications-title"><h3 id="applications-title">登録の申し込み</h3><p>お名前と連絡先を確認して承認してください。承認すると、info@taf-design.com から本人に案内メールを送信します。</p><button id="applications-refresh" type="button" class="secondary">申し込みを更新</button><div id="applications"></div><details><summary>承認メールの送信履歴</summary><p>「送信処理完了」はサーバーが送信を受け付けた状態です。本人の受信箱への到着を保証するものではありません。</p><div id="approval-mails"></div></details></section><p>登録した方だけがログインできます。会員は最大500件まで一覧表示します。</p><details><summary>会員を追加する</summary><form id="user-form"><div class="fields"><label>表示名<input name="name" required maxlength="60"></label><label>メールアドレス<input name="login" type="email" required maxlength="254" autocomplete="off" autocapitalize="none" spellcheck="false" placeholder="例：name@example.com"></label></div><label>会員区分<select name="membership"><option value="regular">通常会員</option><option value="free">無料会員</option></select></label><label>権限<select name="role"><option value="member">一般会員</option><option value="candidate">理事候補</option><option value="director">理事</option><option value="admin">管理者（会員管理・お知らせ投稿可）</option></select></label><label>ログインの案内方法<select name="access_method"><option value="link">専用リンク（入力不要・おすすめ）</option><option value="password">メールアドレスと仮パスワード</option></select></label><small>管理者の追加は、メールアドレスと仮パスワード方式になります。</small><button class="primary">会員を追加して案内を作る</button></form></details><div id="users"></div></section></section>
<footer>じねんネットワーク 会員サイト <span>投稿や参加リンクを会員以外へ共有しないでください。</span></footer></main>
<button class="back-top" id="top" aria-label="ページの先頭へ戻る" hidden>↑</button><dialog id="credential-dialog" aria-labelledby="credential-heading"><h2 id="credential-heading">仮パスワードを発行しました</h2><p id="credential-description">この画面を閉じると再表示できません。本人に個別に伝えてください。</p><p id="credential-user"></p><output id="credential"></output><p id="credential-note">初回ログイン時に変更が必要です。</p><button type="button" class="primary" id="credential-copy">案内文をコピー</button><button type="button" class="secondary" id="credential-close">閉じる</button></dialog><script src="chat.js?v=20260911-prayer"></script></body></html>
