 'use strict';
const $=id=>document.getElementById(id);
const fields={humanity:['人類愛の祈り','回'],vision:['大構想の祈り','回'],return_point:['回帰点の祈り','回'],other_prayer:['その他の祈り','回'],gratitude:['全感謝の祈り','回'],meditation:['瞑想','分'],listening:['聴く行','時間']};
let state,csrf='',revision=0,loadedMonth='',draft=null,dirty=false,busy=false,memberAfter=0,summaryOffset=0,summaryMonth='',historyBefore='',loadGeneration=0;
const normalize=v=>v.trim().replace(/[！-～]/g,c=>String.fromCharCode(c.charCodeAt(0)-0xfee0));
const monthName=m=>m.replace('-', '年')+'月';
function node(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
function status(text,error=false){$('status').textContent=text;$('status').classList.toggle('error',error);if(error)$('status').scrollIntoView({block:'center'});}
function conceal(){dirty=false;draft=null;['personal','management','member-editor'].forEach(id=>$(id).hidden=true);['identity','review-identity','review-values','history','reports','members','totals'].forEach(id=>$(id).replaceChildren());$('report-form').reset();$('member-form').reset();}
async function api(action,data,query=''){
 const r=await fetch('prayer-api.php?action='+action+query,{method:data?'POST':'GET',credentials:'same-origin',cache:'no-store',headers:data?{'Content-Type':'application/json','X-CSRF-Token':csrf}:{},body:data?JSON.stringify(data):undefined});
 let j;try{j=await r.json();}catch{throw new Error('通信結果を確認できません。入力内容を控え、保存済みの記録を読み直してください。');}
 if(!r.ok){if(r.status===401||r.status===403){conceal();$('unavailable').hidden=false;}throw new Error(j.error||'通信できませんでした。');}if(j.csrf)csrf=j.csrf;return j;
}
function receiptText(s){return ({sent:'控えメールの送信処理が完了しました。届かない場合は迷惑メールもご確認ください。',failed:'記録は保存済みですが、控えメールを送れませんでした。メールアドレスを確認し、再送をお試しください。',pending:'記録は保存済みです。控えメールの送信がまだ完了していません。',sending:'記録は保存済みです。控えメールの送信結果は確認中です。届かない場合は担当者にご連絡ください。'})[s]||'記録は保存済みです。';}
function showReceipt(s){$('receipt-note').textContent=receiptText(s);$('receipt-retry').hidden=!['failed','pending'].includes(s);}
function valuesView(r){const box=node('div');const dl=node('dl',undefined,'prayer-values');for(const [k,[name,unit]]of Object.entries(fields)){const line=node('div');line.append(node('dt',name),node('dd',r[k]+' '+unit));dl.append(line);}box.append(dl,node('h3','感想・気づき'),node('p',r.reflection||'記入なし','message-body'));return box;}
async function loadReport(month){
 const generation=++loadGeneration;$('review-button').disabled=true;$('values').disabled=true;loadedMonth='';
 try{const data=await api('report',null,'&month='+encodeURIComponent(month));if(generation!==loadGeneration)return;revision=data.report?Number(data.report.revision):0;loadedMonth=month;$('report-month').value=month;for(const k of Object.keys(fields))$(k).value=data.report?data.report[k]:'0';$('reflection').value=data.report?.reflection||'';$('existing-note').textContent=data.report?'提出済みです。修正すると、この月の合計を置き換えます。二重に加算されません。':'この月はまだ提出していません。';dirty=false;draft=null;$('entry').hidden=false;$('review').hidden=true;$('success').hidden=true;status('');if(data.report){showReceipt(data.report.receipt_status);}}
 finally{if(generation===loadGeneration){$('values').disabled=!loadedMonth;$('review-button').disabled=!loadedMonth;}}
}
async function historyLoad(more=false){const r=await api('history',null,more?'&before='+historyBefore:'');if(!more)$('history').replaceChildren();if(!r.reports.length&&!more)$('history').append(node('p','まだ記録がありません。'));for(const item of r.reports){const row=node('div',undefined,'prayer-row');const a=node('a',monthName(item.month)+'分の記録');a.href='?month='+item.month;row.append(a,node('p','更新回数：'+item.revision+' ／ '+receiptText(item.receipt_status)));$('history').append(row);historyBefore=item.month;}$('history-more').hidden=!r.more;}
$('report-form').addEventListener('input',e=>{if(e.target.id!=='report-month')dirty=true;});
$('report-month').addEventListener('change',async()=>{const month=$('report-month').value;if(!month)return;if(dirty&&!confirm('入力中の内容を破棄して、別の月を開きますか？')){$('report-month').value=loadedMonth;return;}try{await loadReport(month);}catch(e){status(e.message,true);}});
$('reload-report').onclick=async()=>{if(dirty&&!confirm('入力中の内容を破棄して、保存済みの記録を読み直しますか？'))return;try{await loadReport($('report-month').value);}catch(e){status(e.message,true);}};
$('report-form').onsubmit=e=>{e.preventDefault();if(busy||!loadedMonth)return;try{const data={month:loadedMonth,revision,reflection:$('reflection').value};for(const k of Object.keys(fields)){const v=normalize($(k).value);const valid=k==='listening'?/^\d{1,9}(?:\.\d{1,2})?$/.test(v):/^\d{1,9}$/.test(v);if(!valid){$(k).focus();throw new Error(fields[k][0]+'の数値を確認してください。');}data[k]=v;$(k).value=v;}draft=data;$('review-identity').textContent=state.user.name+' さん ／ '+monthName(data.month)+'分';$('review-values').replaceChildren(valuesView(data));$('entry').hidden=true;$('review').hidden=false;history.pushState({prayerReview:true},'',location.href);$('review').focus();$('review').scrollIntoView({block:'start'});status('');}catch(err){status(err.message,true);}};
function returnToEntry(){if(busy)return;$('review').hidden=true;$('entry').hidden=false;draft=null;}
$('edit-report').onclick=()=>{if(history.state?.prayerReview)history.back();else returnToEntry();};
window.addEventListener('popstate',()=>{if(busy){history.replaceState(null,'',location.href);}else returnToEntry();});
$('submit-report').onclick=async()=>{if(busy||!draft)return;busy=true;$('submit-report').disabled=true;$('edit-report').disabled=true;try{const result=await api('save',draft);revision=result.revision;dirty=false;draft=null;$('review').hidden=true;$('entry').hidden=true;$('success').hidden=false;history.replaceState(null,'',location.href);showReceipt(result.receipt_status);$('success').focus();status('');await historyLoad();}catch(e){status(e.message,true);}finally{busy=false;$('submit-report').disabled=false;$('edit-report').disabled=false;}};
$('edit-saved').onclick=async()=>{try{await loadReport(loadedMonth);$('entry').scrollIntoView({block:'start'});}catch(e){status(e.message,true);}};
$('receipt-retry').onclick=async()=>{$('receipt-retry').disabled=true;try{const r=await api('receipt_retry',{month:loadedMonth});showReceipt(r.receipt_status);await historyLoad();}catch(e){status(e.message,true);}finally{$('receipt-retry').disabled=false;}};
async function membersLoad(more=false){if(!more){memberAfter=0;$('members').replaceChildren();}const r=await api('members',null,'&after='+memberAfter);for(const m of r.members){const row=node('div',undefined,'prayer-row');row.append(node('strong',m.name),node('p',m.login),node('p',m.number?'番号 '+m.number+' ／ '+(Number(m.enabled)?'参加登録済み':'利用停止中'):'未登録'));const b=node('button','参加設定','secondary');b.type='button';b.onclick=()=>{$('member-title').textContent=m.name+' さんの参加設定';$('member-id').value=m.id;$('member-number').value=m.number||'';$('member-start').value=m.start_month||state.latest_month;$('member-end').value=m.end_month||'';$('member-enabled').value=m.enabled??1;$('member-editor').hidden=false;$('member-editor').focus();$('member-editor').scrollIntoView({block:'start'});};row.append(b);$('members').append(row);memberAfter=m.id;}$('members-more').hidden=!r.more;}
$('member-form').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{await api('member_save',{user_id:Number($('member-id').value),number:normalize($('member-number').value),start_month:$('member-start').value,end_month:$('member-end').value,enabled:Number($('member-enabled').value)});$('member-editor').hidden=true;await membersLoad();await summaryLoad();status('参加設定を保存しました。');}catch(err){status(err.message,true);}finally{b.disabled=false;}};
async function summaryLoad(more=false){
 if(!more){summaryOffset=0;summaryMonth=$('summary-month').value;$('reports').replaceChildren();}$('csv-link').removeAttribute('href');const r=await api('summary',null,'&month='+encodeURIComponent(summaryMonth)+'&offset='+summaryOffset);
 if(!more){$('summary-count').textContent=monthName(r.month)+'：提出済み '+r.submitted+'名 ／ 対象 '+r.total+'名 ／ 未提出 '+(r.total-r.submitted)+'名';$('totals').replaceChildren();for(const[k,[label,unit]]of Object.entries(fields)){const card=node('div',undefined,'prayer-total');card.append(node('span',label),node('strong',r.totals[k]+' '+unit));$('totals').append(card);}}
 for(const row of r.rows){const card=node('details',undefined,'prayer-row');card.append(node('summary',(row.number??row.participant_number)+' '+(row.name??row.current_name)+' ／ '+(row.id?'提出済み':'未提出')));if(row.id){card.append(valuesView(row),node('p','更新回数：'+row.revision),node('p',receiptText(row.receipt_status)));}else card.append(node('p','この月の報告はまだありません。'));$('reports').append(card);}
 summaryOffset+=r.rows.length;$('summary-more').hidden=!r.more;$('csv-link').href='prayer-api.php?action=csv&month='+encodeURIComponent(summaryMonth);
}
$('summary-form').onsubmit=async e=>{e.preventDefault();e.submitter.disabled=true;try{await summaryLoad();status('');}catch(err){status(err.message,true);}finally{e.submitter.disabled=false;}};
for(const [id,fn] of [['history-more',()=>historyLoad(true)],['members-more',()=>membersLoad(true)],['summary-more',()=>summaryLoad(true)]])$(id).onclick=async()=>{$(id).disabled=true;try{await fn();}catch(e){status(e.message,true);}finally{$(id).disabled=false;}};
async function start(){
 state=await api('state');const admin=state.user.role==='admin',manage=admin&&new URLSearchParams(location.search).get('manage')==='1';$('manage-link').hidden=!admin;$('chat-link').hidden=!admin&&!Number(state.user.chat_access);$('management').hidden=!manage;$('unavailable').hidden=state.eligible||manage;$('personal').hidden=!state.eligible||manage;
 if(manage){$('summary-month').value=state.latest_month;await summaryLoad();await membersLoad();}
 else if(state.eligible){$('identity').textContent='番号 '+state.participant.number+' ／ '+state.user.name+' さん ／ '+state.user.login;const p=state.participant;$('report-month').min=p.start_month;$('report-month').max=p.end_month&&p.end_month<state.latest_month?p.end_month:state.latest_month;let month=new URLSearchParams(location.search).get('month')||$('report-month').max;if(!/^20\d{2}-(0[1-9]|1[0-2])$/.test(month))month=state.latest_month;if(p.start_month>$('report-month').max){$('entry').hidden=true;$('history-section').hidden=true;status('参加開始月が終わると報告できます。');return;}await loadReport(month);await historyLoad();}
 status('');
}
window.addEventListener('beforeunload',e=>{if(dirty||busy){e.preventDefault();e.returnValue='';}});
window.addEventListener('pageshow',e=>{if(e.persisted)location.reload();});
window.addEventListener('pagehide',()=>conceal());
setInterval(async()=>{if(!state||document.hidden||busy)return;try{const fresh=await api('state');if(fresh.user.id!==state.user.id||fresh.user.role!==state.user.role||fresh.eligible!==state.eligible||JSON.stringify(fresh.participant)!==JSON.stringify(state.participant)){conceal();location.reload();}}catch(e){status(e.message,true);}},30000);
start().catch(e=>status(e.message,true));
