<?php
require __DIR__.'/bootstrap.php';
$u=currentUser();
if (!$u || (int)$u['must_change']) {
    $id=max(0,(int)($_GET['id'] ?? 0));
    header('Location: ./?redo='.$id);exit;
}
header('Content-Type: text/html; charset=utf-8');
header("Content-Security-Policy: default-src 'self'; script-src 'self'; style-src 'self'; connect-src 'self'; img-src 'self'; object-src 'none'; base-uri 'none'; form-action 'self'; frame-ancestors 'none'");
?>
<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>REDO MAIL｜じねんネットワーク</title><link rel="stylesheet" href="chat.css?v=20260911-redo"><link rel="stylesheet" href="redo.css?v=20260911-redo"></head><body>
<header class="masthead"><a class="brand" href="redo.php">じねんネットワーク<span>やりなおし会員・REDO MAIL</span></a></header>
<nav class="navigation" aria-label="REDO MAILメニュー"><a href="redo.php">REDO MAIL</a><a href="../ku-fudo-demo/">カリキュラム</a><a id="chat-link" href="./" hidden>チャット</a><a href="?manage=1" id="manage-link" hidden>発行・会員管理</a><a href="prayer.php">祈りの蓄積</a><a href="./?account=1">アカウント</a></nav>
<main><p id="status" role="status" aria-live="polite"></p><section class="section-heading"><div><p class="eyebrow">やりなおし会員</p><h1>REDO MAIL</h1><p id="membership"></p></div></section>
<section id="reader"><div id="issues"></div><a id="older" class="secondary" hidden>以前の号を見る</a><article id="issue" class="card" hidden><a href="redo.php">← 一覧に戻る</a><p id="issue-meta"></p><h2 id="issue-title"></h2><p id="issue-body" class="message-body"></p><a id="pdf-link" class="primary" hidden>PDFを開く・保存する</a></article></section>
<section id="settings" class="card"><h2>メールの配信設定</h2><p>メールを停止しても、有効期間中はサイトで読むことができます。</p><button id="subscription" type="button" class="secondary"></button></section>
<section id="manager" hidden><section class="card"><h2>新しい号を作成</h2><form id="issue-form"><input type="hidden" name="id" value="0"><div class="fields"><label>号数<input name="number" maxlength="20" placeholder="例：614" required></label><label>シリーズ<input name="series" maxlength="30" value="XXⅨ" required></label></div><label>配信日<input name="issued_on" type="date" required></label><label>タイトル<input name="title" maxlength="120" placeholder="例：岩根先生よりメッセージ【統一メール614号】" required></label><label>本文<textarea name="body" rows="12" maxlength="20000" required></textarea></label><label>PDF（任意・10MBまで）<input id="pdf-file" type="file" accept="application/pdf,.pdf"></label><p>まず下書きを保存し、次の画面で内容を確認します。配信日は表示用です。予約配信ではありません。</p><button class="primary">下書きを保存して確認</button><button id="new-issue" type="button" class="secondary">新しい号を入力</button></form></section>
<section class="card" id="preview" hidden><h2>発行前の確認</h2><p id="preview-meta"></p><h3 id="preview-title"></h3><p id="preview-body" class="message-body"></p><a id="preview-pdf" class="secondary" hidden>PDFを確認</a><p id="recipients"></p><p>メールには「今号を読む」ボタンを掲載します。本文・PDFはログイン後に閲覧できます。</p><button type="button" id="publish" class="primary">公開してメールで知らせる</button><button type="button" id="publish-only" class="secondary">公開のみ（メールなし）</button></section>
<section class="card"><h2>発行済み・下書き</h2><div id="admin-issues"></div><a id="admin-older" hidden>以前の号を管理</a></section>
<section id="delivery-panel" class="card" hidden><h2>メールの送信状況</h2><p id="delivery-counts"></p><p>「送信処理完了」はメールサーバーが受け付けた状態です。受信箱への到着を保証するものではありません。</p><button id="send" type="button" class="primary">未送信分の送信を開始・再開</button><button id="stop-send" type="button" class="secondary" hidden>いったん停止</button><button id="retry" type="button" class="secondary">失敗分を再送待ちに戻す</button><p>送信中はこの画面を開いたままにしてください。中断後は再開できます。「結果未確認」は重複送信を避けるため、自動再送しません。</p><div id="delivery-list"></div><button id="delivery-more" type="button" hidden>次の100件</button></section>
<section class="card"><h2>やりなおし会員の管理</h2><p>会費期間は毎年2月1日〜翌年1月31日（仮設定）です。途中入会も終了日は共通です。振込額は実際の金額を入力してください。</p><details><summary>未登録の方を追加</summary><form id="member-form"><label>お名前<input name="name" maxlength="60" required></label><label>メールアドレス<input name="login" type="email" maxlength="254" required></label><button class="primary">やりなおし会員用アカウントを作成</button></form><p>追加だけでは閲覧できません。続けて対象年度と入金情報を登録します。既存の会員は下の一覧から選べます。</p></details><p id="credential" class="message-body" hidden></p><button type="button" id="clear-credential" hidden>案内を閉じる</button><label>対象年度（開始年）<input id="year" type="number" min="2000" max="2100"></label><button id="members-refresh" type="button" class="secondary">この年度の会員を表示</button><p id="period"></p><p id="term-alert"></p><div id="members"></div><button id="members-more" type="button" hidden>次の100人</button></section>
<section class="card" id="term-editor" hidden><h2 id="term-title"></h2><form id="term-form"><input name="user_id" type="hidden"><input name="year" type="hidden"><div class="fields"><label>この年度の入会・利用開始日<input name="joined_on" type="date" required></label><label>入金日<input name="paid_on" type="date" required></label></div><label>銀行振込の入金額（円）<input name="amount" type="number" min="0" max="10000000" required></label><label>この年度の会員資格<select name="enabled"><option value="1">有効</option><option value="0">停止</option></select></label><label>既存のチャット・会員教材も利用できますか<select name="chat_access"><option value="0">利用しない（REDO MAILのみ）</option><option value="1">利用する（両方の会員）</option></select></label><label>管理者メモ<textarea name="note" maxlength="1000" rows="3"></textarea></label><button class="primary">入金・会員資格を保存</button></form><p>翌年度の更新は、対象年度を切り替えて登録します。前年の記録は残ります。入金案内メールは自動送信しません。</p></section></section>
</main><script src="redo.js?v=20260911-redo" defer></script></body></html>
