'use strict';
const $=id=>document.getElementById(id),n=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
let user,csrf='',year,selectedIssue=0,deliveryId=0,memberAfter=0,deliveryAfter=0,sending=false,stop=false;
const statusNames={pending:'未送信',sending:'結果未確認',sent:'送信処理完了',failed:'送信失敗',skipped:'対象外・送信停止'};
function say(s,error=false){$('status').textContent=s;$('status').className=error?'error':'';}
async function api(action,data,query=''){
 const multipart=data instanceof FormData;
 const res=await fetch('redo-api.php?action='+encodeURIComponent(action)+query,{method:data?'POST':'GET',credentials:'same-origin',cache:'no-store',headers:data?{'X-CSRF-Token':csrf,...(multipart?{}:{'Content-Type':'application/json'})}:{},body:data?(multipart?data:JSON.stringify(data)):undefined});
 let out;try{out=await res.json();}catch{throw Error('応答を読み取れません。ファイル容量とサーバー設定を確認してください。');}
 if(!res.ok){if(res.status===401){location.replace('./');}throw Error(out.error||'通信に失敗しました。');}if(out.csrf)csrf=out.csrf;return out;
}
function bind(id,handler){$(id).addEventListener('submit',async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{await handler(e.target);}catch(err){say(err.message,true);}finally{b.disabled=false;}});}
function action(label,fn,cls='secondary'){const b=n('button',label,cls);b.type='button';b.onclick=async()=>{b.disabled=true;try{await fn();}catch(e){say(e.message,true);}finally{b.disabled=false;}};return b;}
function fields(form){return Object.fromEntries(new FormData(form));}
function today(){return new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Tokyo'}).format(new Date());}
async function start(){const s=await api('state');user=s.user;year=s.year;$('year').value=year;$('chat-link').hidden=user.role!=='admin'&&!Number(user.chat_access);$('manage-link').hidden=user.role!=='admin';$('subscription').textContent=Number(user.redo_mail)?'メールの配信を停止する':'メールの配信を再開する';$('membership').textContent=user.role==='admin'?'管理者として閲覧しています。':s.eligible?'会員資格：有効 ／ '+s.period[0]+'〜'+s.period[1]:'現在、有効なやりなおし会員資格がありません。入金・年度について管理者にご確認ください。';
 const manage=new URLSearchParams(location.search).has('manage')&&user.role==='admin';$('manager').hidden=!manage;$('reader').hidden=manage;
 if(manage){$('issue-form').elements.issued_on.value=today();await loadAdminIssues();await loadMembers();}
 else if(s.eligible||user.role==='admin'){const id=new URLSearchParams(location.search).get('id');if(id)await showIssue(Number(id));else await loadIssues();}
}
async function loadIssues(){const before=new URLSearchParams(location.search).get('before')||'';const r=await api('issues',null,before?'&before='+encodeURIComponent(before):'');$('issues').replaceChildren();if(!r.issues.length)$('issues').append(n('p','公開された号はまだありません。'));for(const i of r.issues){const card=n('article',undefined,'card');card.append(n('p','REDO MAIL '+i.series+' No.'+i.number+' ／ '+i.issued_on),n('h2',i.title));const a=n('a','本文を読む →','primary');a.href='?id='+i.id;card.append(a);$('issues').append(card);}$('older').hidden=!r.more;if(r.more)$('older').href='?before='+r.issues.at(-1).id;}
async function showIssue(id){const {issue:i}=await api('issue',null,'&id='+id);$('issue').hidden=false;$('issue-meta').textContent='REDO MAIL '+i.series+' No.'+i.number+' ／ '+i.issued_on;$('issue-title').textContent=i.title;$('issue-body').textContent=i.body;$('pdf-link').hidden=!i.has_pdf;$('pdf-link').href='redo-api.php?action=pdf&id='+i.id;}
async function preview(id){const {issue:i}=await api('issue',null,'&id='+id);selectedIssue=id;$('preview').hidden=false;$('preview-meta').textContent='REDO MAIL '+i.series+' No.'+i.number+' ／ '+i.issued_on;$('preview-title').textContent=i.title;$('preview-body').textContent=i.body;$('preview-pdf').hidden=!i.has_pdf;$('preview-pdf').href='redo-api.php?action=pdf&id='+id;const count=(await api('recipients')).count;$('recipients').textContent='現在のメール配信対象：'+count+'人（有効なやりなおし会員・配信希望者）';$('publish').hidden=Number(i.published)!==0;$('publish-only').hidden=Number(i.published)!==0;$('preview').scrollIntoView({behavior:'smooth'});}
async function loadAdminIssues(){const before=new URLSearchParams(location.search).get('before')||'';const r=await api('issues',null,before?'&before='+encodeURIComponent(before):'');$('admin-issues').replaceChildren();for(const i of r.issues){const card=n('article',undefined,'card');card.append(n('b',i.title),n('p','No.'+i.number+' ／ '+i.issued_on+' ／ '+({0:'下書き',1:'公開中',2:'公開停止'})[i.published]));const a=n('div',undefined,'redo-actions');a.append(action('内容を確認',()=>preview(i.id)));if(!Number(i.published))a.append(action('編集する',async()=>{const {issue:d}=await api('issue',null,'&id='+i.id);for(const key of ['id','number','series','issued_on','title','body'])$('issue-form').elements[key].value=d[key];$('pdf-file').value='';$('issue-form').scrollIntoView({behavior:'smooth'});}));else a.append(action('送信状況',()=>deliveries(i.id)));if(Number(i.published)===1)a.append(action('公開を停止',async()=>{if(!confirm('本文・PDFの閲覧と未送信メールを停止しますか？送信済みメールは取り消せません。'))return;await api('unpublish',{id:i.id});await loadAdminIssues();say('公開を停止しました。');}));card.append(a);$('admin-issues').append(card);}$('admin-older').hidden=!r.more;if(r.more)$('admin-older').href='?manage=1&before='+r.issues.at(-1).id;}
bind('issue-form',async f=>{const data=fields(f),pdf=$('pdf-file').files[0];if(pdf&&pdf.size>10*1024*1024)throw Error('PDFは10MB以内にしてください。');const r=await api('issue_save',{...data,id:Number(data.id)});f.elements.id.value=r.id;if(pdf){const fd=new FormData();fd.append('id',r.id);fd.append('pdf',pdf);await api('upload',fd);$('pdf-file').value='';}await loadAdminIssues();await preview(r.id);say('下書きを保存しました。まだ公開・送信していません。');});
$('new-issue').onclick=()=>{$('issue-form').reset();$('issue-form').elements.id.value=0;$('issue-form').elements.issued_on.value=today();$('preview').hidden=true;selectedIssue=0;};
async function publish(notify){if(!selectedIssue)return;const count=(await api('recipients')).count;if(!confirm(notify?'この号を公開し、現在の対象'+count+'人へ案内メールを送信しますか？':'この号を公開しますか？メールは送信しません。'))return;const id=selectedIssue;await api('publish',{id,notify,confirmed:true});$('preview').hidden=true;await loadAdminIssues();await deliveries(id);say(notify?'公開しました。メールを送信します。':'公開しました。メールは送信していません。');if(notify)await send();}
for(const [id,notify] of [['publish',true],['publish-only',false]])$(id).onclick=async()=>{$(id).disabled=true;try{await publish(notify);}catch(e){say(e.message,true);}finally{$(id).disabled=false;}};
async function deliveries(id,more=false){if(!more){deliveryId=id;deliveryAfter=0;$('delivery-list').replaceChildren();}const r=await api('deliveries',null,'&id='+id+'&after='+deliveryAfter);$('delivery-panel').hidden=false;$('delivery-counts').textContent=r.counts.map(c=>statusNames[c.status]+'：'+c.count+'件').join(' ／ ')||'メール送信の対象はありません。';for(const d of r.deliveries)$('delivery-list').append(n('p',d.name+' ／ '+d.recipient+' ／ '+statusNames[d.status]));if(r.deliveries.length)deliveryAfter=r.deliveries.at(-1).id;$('delivery-more').hidden=r.deliveries.length<100;}
async function send(){if(sending)return;sending=true;stop=false;$('send').disabled=true;$('stop-send').hidden=false;const id=deliveryId;try{let remaining=1;while(remaining&&!stop){const r=await api('send_batch',{id});remaining=r.remaining;await deliveries(id);if(remaining&&!stop)await new Promise(resolve=>setTimeout(resolve,3000));}say(stop?'送信を一時停止しました。未送信分は再開できます。':'送信処理が終了しました。結果を確認してください。');}finally{sending=false;$('send').disabled=false;$('stop-send').hidden=true;}}
$('send').onclick=()=>send().catch(e=>say(e.message,true));$('stop-send').onclick=()=>{stop=true;};$('retry').onclick=async()=>{try{if(!confirm('送信失敗分を再送待ちに戻しますか？'))return;await api('retry_failed',{id:deliveryId});await deliveries(deliveryId);say('再送待ちにしました。「送信を開始・再開」を押してください。');}catch(e){say(e.message,true);}};$('delivery-more').onclick=()=>deliveries(deliveryId,true).catch(e=>say(e.message,true));
async function loadMembers(more=false){if(!more){year=Number($('year').value);memberAfter=0;$('members').replaceChildren();}const r=await api('members',null,'&year='+year+'&after='+memberAfter);$('period').textContent=year+'年度：'+r.period[0]+'〜'+r.period[1];const days=Math.ceil((Date.parse(r.period[1]+'T23:59:59+09:00')-Date.now())/86400000);$('term-alert').textContent=days<0?'この年度は終了しています。':days<=30?'この年度の終了まで30日以内です。翌年度の更新をご確認ください。':'';for(const m of r.members){const row=n('div',undefined,'member-line');row.append(n('b',m.name),n('p',m.login),n('p',!m.term_id?'この年度は未登録':!Number(m.enabled)?'資格停止':days<0?'期限切れ':m.joined_on>today()?'開始前':'有効'),n('p',m.term_id?'入金：'+m.paid_on+' ／ '+Number(m.amount).toLocaleString()+'円':''));row.append(action(m.term_id?'入金・資格を編集':'この年度に登録',()=>editTerm(m,r.period)));$('members').append(row);}if(r.members.length)memberAfter=r.members.at(-1).id;$('members-more').hidden=!r.more;}
function editTerm(m,period){const f=$('term-form');f.elements.user_id.value=m.id;f.elements.year.value=year;f.elements.joined_on.min=period[0];f.elements.joined_on.max=period[1];f.elements.joined_on.value=m.joined_on||[period[0],today(),period[1]].sort()[1];f.elements.paid_on.value=m.paid_on||today();f.elements.amount.value=m.amount??'';f.elements.enabled.value=m.enabled??1;f.elements.chat_access.value=m.chat_access;f.elements.note.value=m.note||'';$('term-title').textContent=m.name+' さん ／ '+year+'年度';$('term-editor').hidden=false;$('term-editor').scrollIntoView({behavior:'smooth'});}
bind('term-form',async f=>{const d=fields(f);if(!confirm('この年度の入金・会員資格を保存しますか？'))return;await api('term_save',{...d,user_id:Number(d.user_id),year:Number(d.year),amount:Number(d.amount),enabled:Number(d.enabled),chat_access:Number(d.chat_access)});await loadMembers();say('保存しました。更新時も年度を選んで登録できます。');$('term-editor').hidden=true;});
bind('member-form',async f=>{const d=fields(f),r=await api('member_create',d);$('credential').hidden=false;$('clear-credential').hidden=false;$('credential').textContent=d.name+' さん\nログイン：'+new URL('./',location.href).href+'\nメールアドレス：'+d.login+'\n仮パスワード：'+r.temporary_password+'\n初回ログインで8文字以上のパスワードに変更してください。\nこの案内を本人に個別にお伝えください。';f.reset();await loadMembers();say('追加しました。続けて対象年度・入金情報を登録してください。');});
$('clear-credential').onclick=()=>{$('credential').textContent='';$('credential').hidden=true;$('clear-credential').hidden=true;};$('members-refresh').onclick=()=>loadMembers().catch(e=>say(e.message,true));$('members-more').onclick=()=>loadMembers(true).catch(e=>say(e.message,true));
$('subscription').onclick=async()=>{try{const enabled=Number(user.redo_mail)?0:1;if(!confirm(enabled?'メールの配信を再開しますか？':'メールの配信を停止しますか？'))return;await api('subscription',{enabled});user.redo_mail=enabled;$('subscription').textContent=enabled?'メールの配信を停止する':'メールの配信を再開する';say('配信設定を保存しました。');}catch(e){say(e.message,true);}};
window.addEventListener('pagehide',()=>{stop=true;$('credential').textContent='';});window.addEventListener('pageshow',e=>{if(e.persisted)location.reload();});start().catch(e=>say(e.message,true));

setInterval(()=>{if(document.hidden||!user)return;api('state').then(s=>{if(s.user.role!==user.role||(user.role!=='admin'&&!s.eligible))location.reload();}).catch(()=>location.reload());},30000);
