'use strict';
const KEY='jinen-member-design-preview-1';
const initial={watched:[false,false,false,false,false,false],notes:['','','','','',''],applications:{},recommended:false,posts:[]};
let state;try{state=JSON.parse(sessionStorage.getItem(KEY))||structuredClone(initial);}catch{state=structuredClone(initial)}
const lessons=['自明行とは何か（前半）','自明行とは何か（後半）','自明行の導入','正しい喜びの自覚','自明行の準備','自明行の落とし穴'];
const meetings=[{id:'fukuoka',name:'福岡地区 学びの会',date:'2026年10月4日（日）14:00〜',area:'福岡',fee:'1,000円（仮）',body:'お話を聞き、日々の気づきを分かち合う会です。参加条件と入金を担当者が確認してから、ご案内します。'},{id:'intro',name:'はじめての方向け お話の会',date:'2026年10月11日（日）10:00〜',area:'全国',fee:'無料（仮）',body:'初めて参加する方のための交流会です。無料の会ですが、お申し込みと担当者の承認が必要です。'}];
const main=document.getElementById('main'),dlg=document.getElementById('dialog');const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const menu={home:'マイページ',courses:'カリキュラム',records:'視聴記録・自分のメモ',meetings:'会議の案内・申し込み',chat:'チャット',redo:'REDO MAIL',prayer:'祈りの蓄積',account:'登録情報'};
const badge=id=>{const s=state.applications[id];return s==='approved'?'<span class="badge approved">参加承認済み</span>':s==='pending'?'<span class="badge waiting">承認待ち</span>':s==='declined'?'<span class="badge declined">今回は見送り</span>':'<span class="badge">申し込み受付中</span>'};
const save=()=>{try{sessionStorage.setItem(KEY,JSON.stringify(state));}catch{}};
let toastTimer;function toast(text){document.getElementById('toast').textContent=text;clearTimeout(toastTimer);toastTimer=setTimeout(()=>document.getElementById('toast').textContent='',3500)}
function modal(html){document.getElementById('dialog-body').innerHTML=html;dlg.showModal()}
document.getElementById('close').onclick=()=>dlg.close();
function link(href,text,secondary=false){return `<a class="button${secondary?' secondary':''}" href="#${href}">${text}</a>`}
function heading(title,sub=''){return `<h1>${title}</h1>${sub?`<p class="sub">${sub}</p>`:''}`}
function meetingCard(m){return `<article class="card"><div class="meta">${badge(m.id)}<span class="badge">${m.area}</span></div><h3>${m.name}</h3><p class="date">${m.date}</p><p>${m.fee}</p>${link('meeting/'+m.id,state.applications[m.id]==='approved'?'承認済みの案内を開く':'内容・申し込み状況を見る',true)}</article>`}
function render(){const route=location.hash.slice(1)||'home', [page,arg]=route.split('/');document.getElementById('side').innerHTML=Object.entries(menu).map(([k,v])=>`<a href="#${k}" ${k===page?'aria-current="page"':''}>${v}</a>`).join('');document.querySelectorAll('.bottom a').forEach(a=>{a.removeAttribute('aria-current');if(a.hash==='#'+page||(page==='lesson'&&a.hash==='#courses')||(page==='meeting'&&a.hash==='#meetings'))a.setAttribute('aria-current','page')});const done=state.watched.filter(Boolean).length;const next=Math.max(0,state.watched.findIndex(x=>!x));
if(page==='home'){
 main.innerHTML=heading('会員サンプル A さんのマイページ','今日も、ご自身のペースで学びましょう。')+`<section class="hero"><p class="eyebrow">${state.recommended?'管理者からご案内されたコース':'あなたのカリキュラム'}</p><h2>人間やりなおし・入門</h2><p>${done===6?'全6レッスンのチェックが完了しました。振り返りも大切に。':done===0?'まずは最初のレッスンから。感じたことを、ご自身の言葉で残せます。':'前回の続きから、少しずつ進めましょう。'}</p><div class="hero-bottom">${link(done===6?'records':'lesson/'+next,done===6?'学習の記録を振り返る →':done===0?'最初のレッスンを開く →':'続きから学ぶ →')}<div class="progress"><strong>${done}</strong> / 6 レッスン<progress value="${done}" max="6" aria-label="学習の進み具合"></progress></div></div></section><div class="quick"><a href="#records">視聴記録・メモ<small>これまでの学びを振り返る</small></a><a href="#chat">チャットを開く<small>皆さんの投稿・お知らせ</small></a><a href="#meetings">会議の案内を見る<small>内容を確認して申し込む</small></a></div><div class="heading"><h2>会議のご案内</h2><a href="#meetings">すべて見る →</a></div><div class="grid">${meetings.map(meetingCard).join('')}</div><p class="note">お申し込み後、担当者が確認します。参加の案内は承認された方に表示します。</p><div class="heading"><h2>お知らせ</h2></div><section class="card"><a class="list-link" href="#notice"><span><small>2026.09.13 · お知らせの見本</small>会員サイトの使い方について</span><span>→</span></a><a class="list-link" href="#redo"><span>REDO MAIL<small>やりなおし会員の読み物・PDF</small></span><span>→</span></a><a class="list-link" href="#prayer"><span>祈りの蓄積<small>月ごとの実践を報告する</small></span><span>→</span></a><a class="list-link" href="#account"><span>登録情報・メールの受信設定</span><span>→</span></a></section>`;
}else if(page==='courses'||page==='records'){
 main.innerHTML=heading(page==='courses'?'カリキュラム':'視聴記録・自分のメモ',`人間やりなおし・入門 ／ ${done} / 6 レッスン`)+`<p class="note">視聴済みチェックは、ご自身で保存する方式です。</p>`+lessons.map((title,i)=>`<article class="card lesson"><span class="number">${String(i+1).padStart(2,'0')}</span><div class="grow"><h3>${title}</h3><span class="badge ${state.watched[i]?'approved':''}">${state.watched[i]?'視聴済み':'未チェック'}</span>${page==='records'&&state.notes[i]?`<p class="sub">${esc(state.notes[i]).slice(0,180)}</p>`:''}</div>${link('lesson/'+i,page==='records'?'メモを見る・書く':'レッスンを開く',true)}</article>`).join('');
}else if(page==='lesson'&&/^\d$/.test(arg)&&Number(arg)<6){const i=Number(arg);
 main.innerHTML=`<a class="back" href="#courses">← カリキュラムへ戻る</a>`+heading(lessons[i],`人間やりなおし・入門 ／ レッスン ${i+1}`)+`<div class="video"><div><strong>動画の表示位置</strong><small>今回は画面・操作の確認用です。</small><button id="video-demo">視聴操作を試す ▷</button></div></div><section class="card"><h2>今回の学びを残す</h2><form id="learning-form"><label class="check"><input id="watched" type="checkbox" ${state.watched[i]?'checked':''}>このレッスンを視聴した</label><label for="memo">自分のメモ</label><textarea id="memo" rows="5" maxlength="5000" placeholder="印象に残ったことや、気づいたことを自由にどうぞ。">${esc(state.notes[i])}</textarea><p class="note">管理者は視聴状況を確認できます。本人のメモは管理画面には表示しません。</p><button>チェックとメモを保存する</button><p class="note">この見本では、同じタブ内の仮データとして保存します。</p></form></section><div class="actions">${link('home','マイページに戻る',true)}${i<5?link('lesson/'+(i+1),'次のレッスン →',true):''}</div>`;
 document.getElementById('learning-form').onsubmit=e=>{e.preventDefault();state.watched[i]=document.getElementById('watched').checked;state.notes[i]=document.getElementById('memo').value;save();toast('視聴チェックとメモを保存しました（見本）')};document.getElementById('video-demo').onclick=()=>toast('動画を見た後に、下のチェックとメモを保存する流れです。');
}else if(page==='meetings'){
 main.innerHTML=heading('会議の案内・申し込み','参加したい会の内容と条件をご確認ください。')+`<form class="filters" id="meeting-filter"><label>地区<select id="meeting-area"><option value="">すべて</option><option>福岡</option><option>全国</option></select></label><label>申し込み状況<select id="meeting-status"><option value="">すべて</option><option value="pending">承認待ち</option><option value="approved">承認済み</option></select></label><button>表示する</button></form><div id="meeting-list" class="grid">${meetings.map(meetingCard).join('')}</div>`;document.getElementById('meeting-filter').onsubmit=e=>{e.preventDefault();const area=document.getElementById('meeting-area').value,status=document.getElementById('meeting-status').value;const rows=meetings.filter(m=>(!area||m.area===area)&&(!status||state.applications[m.id]===status));document.getElementById('meeting-list').innerHTML=rows.length?rows.map(meetingCard).join(''):'<p class="empty">該当する会議はありません。</p>'};
}else if(page==='meeting'&&meetings.some(m=>m.id===arg)){const m=meetings.find(m=>m.id===arg),s=state.applications[arg];
 main.innerHTML=`<a class="back" href="#meetings">← 会議の案内へ戻る</a>`+heading(m.name)+`<section class="card"><div class="meta">${badge(arg)}<span class="badge">${m.area}</span></div><p class="date">${m.date}</p><h3>参加費：${m.fee}</h3><p>${m.body}</p><p class="note">日程・料金・内容はすべて画面確認用の仮情報です。</p></section><section class="card">${s==='approved'?`<h2>参加が承認されました</h2><p>本番では、こちらとご本人へのメールで参加方法をご案内します。</p><button id="join">Zoomに参加する（見本）</button>`:s==='pending'?`<h2>お申し込みを受け付けました</h2><p>現在、担当者が確認中です。承認後に参加の案内が届きます。</p><button disabled>承認待ちです</button><div class="actions"><button id="cancel" class="secondary">申し込みを取り消す</button></div>`:s==='declined'?`<h2>今回は参加を見送ることになりました</h2><p>参加条件については担当者へご確認ください。</p>`:`<h2>参加を申し込む</h2><p>申し込みだけでは参加は確定しません。${arg==='fukuoka'?'有料の会は担当者が入金状況も確認します。':'無料の会も担当者の承認が必要です。'}</p><button id="apply">この会議に申し込む</button>`}</section><div class="adminbar">確認用：<a href="#admin">管理者側で申し込みを確認する →</a></div>`;
 if(document.getElementById('apply'))document.getElementById('apply').onclick=()=>{modal(`<h2>お申し込み内容の確認</h2><p>${m.name}</p><p>${m.date}</p><p>参加費：${m.fee}</p><p>担当者の承認後に参加できます。</p><button id="confirm-apply">この内容で申し込む（見本）</button>`);document.getElementById('confirm-apply').onclick=()=>{state.applications[arg]='pending';save();dlg.close();render();toast('承認待ちになりました（見本）')}};
 if(document.getElementById('cancel'))document.getElementById('cancel').onclick=()=>{delete state.applications[arg];save();render();toast('申し込みを取り消しました（見本）')};
 if(document.getElementById('join'))document.getElementById('join').onclick=()=>modal('<h2>承認後の参加ボタンの見本</h2><p>実際のZoomには接続しません。本番では、承認を受けた本人だけが参加リンクを取得できます。</p>');
}else if(page==='admin'){
 const count=Object.values(state.applications).filter(x=>x==='pending').length;
 main.innerHTML=`<div class="adminbar">管理者側の確認用画面 · <a href="#home">会員マイページへ戻る →</a></div>`+heading('申し込み・学習の管理','会員側で行った操作が、こちらに反映される見本です。')+`<div class="grid"><section class="card"><p class="eyebrow">会議の申し込み</p><h2>承認待ち ${count}件</h2><p>条件・入金を確認してから承認します。</p></section><section class="card"><p class="eyebrow">会員サンプル A さん</p><h2>視聴済み ${done} / 6</h2><p>福岡地区 · 無料会員</p><p class="note">本人のメモは取得・表示しません。</p></section></div><div class="heading"><h2>会議の申し込み一覧</h2></div>`+meetings.filter(m=>state.applications[m.id]).map(m=>`<section class="card"><div class="row"><h3>${m.name}</h3>${badge(m.id)}</div><p>会員サンプル A さん ／ ${m.fee}</p>${state.applications[m.id]==='pending'?`<label class="check"><input type="checkbox" id="check-${m.id}">${m.id==='fukuoka'?'参加条件と入金状況を確認した':'参加条件を確認した'}</label><div class="actions"><button data-approve="${m.id}">参加を承認する</button><button data-decline="${m.id}" class="secondary">今回は見送る</button></div>`:`<button data-mail="${m.id}" class="secondary">本人への通知メールの見本</button>`}</section>`).join('')+(Object.keys(state.applications).length?'':'<div class="card empty">申し込みはまだありません。会員側で会議に申し込むと、ここに表示されます。</div>')+`<div class="heading"><h2>学習コースの案内</h2></div><section class="card"><h3>会員サンプル A さん</h3><p>人間やりなおし・入門</p><button id="recommend">このコースを本人に案内する（見本）</button><p class="note">本人のマイページに「管理者からご案内されたコース」と表示します。</p></section><p><a href="../admin-preview/index.html">会員検索など、管理画面全体の見本を見る →</a></p>`;
 document.querySelectorAll('[data-approve]').forEach(b=>b.onclick=()=>{const id=b.dataset.approve;if(!document.getElementById('check-'+id).checked){toast('参加条件・入金状況の確認にチェックしてください。');return;}state.applications[id]='approved';save();render();toast('承認しました。会員側にも反映しました（見本）')});document.querySelectorAll('[data-decline]').forEach(b=>b.onclick=()=>{state.applications[b.dataset.decline]='declined';save();render();toast('見送りに変更しました（見本）')});document.querySelectorAll('[data-mail]').forEach(b=>b.onclick=()=>modal(`<h2>通知メールの見本</h2><p>会員サンプル A 様</p><p>${meetings.find(m=>m.id===b.dataset.mail).name}</p><p>${state.applications[b.dataset.mail]==='approved'?'参加が承認されました。マイページで参加方法をご確認ください。':'今回は参加を見送ることとなりました。担当者へご確認ください。'}</p><p class="note">メールは送信していません。</p>`));document.getElementById('recommend').onclick=()=>{state.recommended=true;save();toast('会員のマイページに案内を反映しました（見本）')};
}else if(page==='curriculum'){
 main.innerHTML=heading('学びと交流の広場','じねんネットワークのカリキュラムへようこそ。')+`<section class="hero"><p class="eyebrow">入門コース</p><h2>自分を見つめる、学びの入り口</h2><p>動画で学び、言葉にして振り返る。全6レッスンを通して、学びを進めます。</p>${link('home','マイページで学びを始める →')}</section><section class="card"><h2>視聴記録・メモを残す方はマイページへ</h2><p>これはカリキュラムから会員ページへ進む流れの見本です。実際のカリキュラムページは変更していません。</p>${link('home','会員マイページを開く',true)}</section>`;
}else if(page==='chat'){
 main.innerHTML=heading('チャット','投稿画面の見本です。実際の会員には公開されません。')+`<section class="card"><h3>運営からのお知らせ（見本）</h3><p>皆さんの気づきや感想をお寄せください。</p></section>`+state.posts.map(p=>`<section class="card"><span class="badge waiting">承認待ち（見本）</span><p>${esc(p)}</p></section>`).join('')+`<form id="chat-form" class="card"><h2>メッセージを投稿</h2><p>無料会員の投稿は管理者が確認してから公開します。</p><textarea id="chat-text" rows="4" maxlength="3000" required></textarea><div class="actions"><button>投稿を申し込む（見本）</button></div></form>`;document.getElementById('chat-form').onsubmit=e=>{e.preventDefault();const t=document.getElementById('chat-text').value.trim();if(t){state.posts.push(t);save();render();toast('仮の投稿を承認待ちにしました')}};
}else if(page==='redo'){
 main.innerHTML=heading('REDO MAIL','やりなおし会員の読み物・PDF')+`<section class="card"><h2>やりなおし会員について</h2><p>通常の会員資格とは別の、有料の会員資格です。対象の方に最新号と過去号を表示する予定です。</p><p class="note">この仮の会員には資格を設定していません。限定の本文やPDFは表示しません。</p>${link('home','マイページへ戻る',true)}</section>`;
}else if(page==='prayer'){
 main.innerHTML=heading('祈りの蓄積','月ごとの実践を、ご自身のペースで。')+`<section class="card"><h2>参加設定をご確認ください</h2><p>担当者が参加番号と参加期間を設定した方に、入力欄とこれまでの記録を表示する予定です。</p><p class="note">この仮の会員には参加資格を設定していません。</p>${link('home','マイページへ戻る',true)}</section>`;
}else if(page==='account'){
 main.innerHTML=heading('登録情報')+`<section class="card"><h2>会員サンプル A さん</h2><p>無料会員 ／ 福岡地区</p><p>sample-a@example.com（仮のアドレス）</p><p class="note">実際の名前・メール・パスワードは入力しないでください。</p></section><section class="card"><h2>確認用データの操作</h2><p>操作したチェック・メモ・申し込みを初期状態に戻せます。</p><button id="reset-demo" class="secondary">見本の操作データをリセット</button></section>`;document.getElementById('reset-demo').onclick=()=>{modal('<h2>見本の操作データをリセットしますか？</h2><p>このタブ内で試したメモ・チェック・申し込みだけを消します。</p><button id="reset-confirm">リセットする</button>');document.getElementById('reset-confirm').onclick=()=>{state=structuredClone(initial);save();dlg.close();render();toast('見本を初期状態に戻しました')}};
}else if(page==='notice'){
 main.innerHTML=`<a class="back" href="#home">← マイページへ戻る</a>`+heading('会員サイトの使い方について')+`<section class="card"><p>「続きから学ぶ」からレッスンを開き、視聴チェックとご自身のメモを保存できます。</p><p>会議への参加は申し込み後、担当者の承認をお待ちください。</p><p class="note">これはお知らせの見本です。</p></section>`;
}else{location.hash='home';return;}
 document.title=(page==='admin'?'管理者側の見本':menu[page]||'マイページ')+'｜じねんネットワーク';window.scrollTo(0,0);
}
addEventListener('hashchange',()=>{if(dlg.open)dlg.close();render();main.focus()});render();
